#! /bin/sh

export HOST=Location/Of/Website/compiled

buildcast () {

    cd Location/Of/CloneBranchBeta
    git fetch origin androidui
    git reset --hard FETCH_HEAD
    export SHA=`git rev-parse HEAD`
    export HASH=`echo $SHA | cut -c1-7`
    if [ ! -e $HOST/reicast-emulator-$HASH.apk ]; then
        echo -n $SHA > shell/android/assets/build
        sh shell/android/tools/buildbot.sh $HASH
    fi
    cd Location/Of/CloneBranchMaster
    git fetch origin master
    git reset --hard FETCH_HEAD
    export SHA2=`git rev-parse HEAD`
    export HASH2=`echo $SHA2 | cut -c1-7`
    if [ ! -e $HOST/reicast-emulator-$HASH2.apk ]; then
        echo -n $SHA2 > shell/android/assets/build
        sh shell/android/tools/buildbot.sh $HASH2
    fi

}

buildcast

exit 0